POST https://cloud-lingo-api.pyutasane.com
Content-Type: application/json

{
  "sourceLang": "en",
  "targetLang": "th",
  "sourceText": "What are you doing today?"
}

###

POST https://cloud-lingo-api.pyutasane.com
Content-Type: application/json

{
  "sourceLang": "es",
  "targetLang": "fr"
}

###

GET https://cloud-lingo-api.pyutasane.com
Content-Type: application/json
