POST https://irte3wveff.execute-api.us-east-1.amazonaws.com/prod/translation
Content-Type: application/json

{
  "sourceLang": "en",
  "targetLang": "th",
  "sourceText": "What are you doing today?"
}

###

POST https://irte3wveff.execute-api.us-east-1.amazonaws.com/prod/translation
Content-Type: application/json

{
  "sourceLang": "es",
  "targetLang": "fr"
}

###

GET https://irte3wveff.execute-api.us-east-1.amazonaws.com/prod/translation
Content-Type: application/json
